repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
        - id: seed-isort-config
    - repo: https://github.com/timothycrosley/isort
      rev: 5.6.4
      hooks:
        - id: isort

    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
        - id: black

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
        - id: flake8
          types:
            - python

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.790'
      hooks:
      - id: mypy
        files: toki/
