FROM continuumio/miniconda3

ARG PYTHON_VERSION
ADD docker/environment-dev.yml /

RUN sed -i "s/-\ python$/-\ python=${PYTHON_VERSION}/" /environment-dev.yml

RUN conda config --add channels conda-forge \
  && conda update --all --yes --quiet \
  && conda install --yes conda-build \
  && conda clean -afy

RUN conda env create --name toki-env --file /environment-dev.yml \
  && conda clean -afy

RUN echo 'source /opt/conda/bin/activate toki-env && exec "$@"' > activate.sh

COPY . /toki
WORKDIR /toki

RUN bash /activate.sh pip install -e . --no-deps --ignore-installed --no-cache-dir

ENTRYPOINT ["bash", "/activate.sh"]
