
name: docs

# Only run this when the "main" branch changes
on:
  push:
    branches: [ main ]


# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Install the pre-release of jupyter book for now until it is "officially" released
    - name: Install Jupyter Book
      run: |
        pip install -r requirements_dev.txt
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build docs/
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
